#!/bin/sh

idx=$2
test -n "$idx" || exit 1
idx=$((16 + $idx))
mnvm_node_id=$(( 100 + $idx ))
tag=ubuntu-16
#idbase=ubuntu-16.00@base
#force=1

. ./my-vmctl-preset-subr

if test "$1" = image
then
    clone_linux_preset

elif test "$1" = configure
then
    configure_linux_ubuntu

else
    echo `basename $0` image IDX
    echo `basename $0` configure IDX
fi
