#!/bin/sh

#set -x
idx=$2
test -n "$idx" || exit 1
idx=$((16 + $idx))
mnvm_node_id=$(( 100 + $idx ))

tag=ubuntu-16
iso=ubuntu-16.04.4-server-amd64.iso
idbase=${tag}.10@base

#grubr=grub.conf-ubuntu-run
#grubi=grub.conf-ubuntu-install

. ./my-vmctl-preset-subr
run_simple_linux_preset $*
