#!/bin/sh

#MY_VMCTL_HOSTENV=skyrta
MY_VMCTL_HOSTENV=big
. ./my-vmctl-preset-hostenv

MY_VMCTL_PLATENV=centos-7
. ./my-vmctl-preset-platenv

mnvm_size=64G
. ./my-vmctl-preset-subr
eval $mnvm_simple_preset $*
