#!/bin/sh
set -x
set -e

if test "$1" = 1
then
    timedatectl set-local-rtc true
    timedatectl set-ntp true
    timedatectl status

    sfdisk /dev/sda <<EOD
label: gpt
label-id: 2156F372-028E-0B40-87D4-911BE15179A5
device: /dev/sda
unit: sectors
first-lba: 2048
last-lba: 134217694

/dev/sda1 : start=        2048, size=     1048576, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=6B593094-A4A3-2E4D-AD1C-A73A3DDECAFE
/dev/sda2 : start=     1050624, size=   131069952, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, uuid=56F9E952-159B-8F48-81CD-20D1D1D4C070
/dev/sda3 : start=   132120576, size=     2097119, type=0657FD6D-A4AB-43C4-84E5-0933C84B4F4F, uuid=8102F535-D26A-4D4B-8EEE-E458B2074BB6
EOD

    mkfs.fat -F32 /dev/sda1
    mkfs.ext4 /dev/sda2
    mount /dev/sda2 /mnt
    mkswap /dev/sda3
    swapon /dev/sda3
    mkdir -p /mnt/boot /mnt/config /mnt/etc

    # boot
    mount /dev/sda1 /mnt/boot

    # config
    mount /dev/sdb /mnt/config
    /bin/sh "/mnt/config/`basename $0`" 2

elif test "$1" = 2
then
    cp /mnt/config/etc/pacman.d/mirrorlist /etc/pacman.d/
    pacstrap /mnt base base-devel openssh vim-minimal git
    rm /mnt/etc/pacman.d/mirrorlist
    ln -s /config/etc/pacman.d/mirrorlist /mnt/etc/pacman.d/

    # etc
    genfstab -U /mnt >>/mnt/etc/fstab

    # chroot
    arch-chroot /mnt /bin/sh "/config/`basename $0`" 3

elif test "$1" = 3
then
    bootctl --path /boot install
    cat >/boot/loader/loader.conf <<EOD
default arch
timeout 10
console-mode max
EOD
    cat >/boot/loader/entries/arch.conf <<EOD
title   Mn Arch
efi   /vmlinuz-linux
options initrd=/initramfs-linux.img root=/dev/sda2
EOD

    rm -f /etc/hostname
    ln -s /config/etc/hostname /etc/
    ln -s /config/etc/netctl/ether /etc/netctl/

    ln -sf /usr/share/zoneinfo/Europe/Kiev /etc/localtime

    netctl enable ether
    systemctl enable netctl
    systemctl enable sshd

    sed -i.bak -E -e 's/^#(en_US.UTF-8.+)$/\1/' -e 's/^#(uk_UA.UTF-8.+)/\1/' /etc/locale.gen
    locale-gen

    systemd-firstboot --root=/ \
        --hostname=`cat /etc/hostname` \
        --timezone=Europe/Kiev \
        --locale=uk_UA.UTF-8 \
        --locale-messages=uk_UA.UTF-8
    hwclock --systohc

else
    echo "Usage: `basename $0` 1|2|3"
    exit 1
fi
