#!/bin/sh

mnhnet=`mnhnet`
#big
#MNVMCTL_DDEV_UFS=1
#mnvm_net=${mnhnet}.2
#skyrta
mnvm_net=${mnhnet}.3

#set -x
idx=$2
test -n "$idx" || exit 1
idx=$((16 + $idx))
mnvm_node_id=$(( 100 + $idx ))

tag=ubuntu-16
iso=ubuntu-18.04-server-amd64.iso
idbase=${tag}.10@base

#grubr=grub.conf-ubuntu-run
#grubi=grub.conf-ubuntu-install

. ./my-vmctl-preset-subr
run_simple_uefi_preset $*
