#!/bin/sh

R=/skyrta/vm
D=/dev/zvol/skyrta

if zpool list >/dev/null 2>&1
then
    if test -z "$MY_VMCTL_DDEV_UFS"
    then
        _zfs=1
    fi
fi
#export _zfs

newvol () {
    local _vol _name _size
    _name=$1
    _size=$2
    if test -n "$_zfs"
    then
        _vol=skyrta/$_name
        zfs destroy $_vol
        zfs create -V $_size $_vol
        _vol=/dev/zvol/$_vol
    else
        _vol=$_name
        rm -f $_vol && truncate -s $_size $_vol
    fi
    echo $_vol
}

getvol () {
    local _vol _name
    _name=$1
    if test -n "$_zfs"
    then
        _vol=/dev/zvol/skyrta/$_name
    else
        _vol=$_name
    fi
    echo $_vol
}

run_simple_linux_preset () {
    local _cmd _d _g _ddev _devmapi _devmapr

    my-vmctl destroy $name

    _devmapi=device.map-${id}.install
    _devmapr=device.map-${id}.run

    cat > device.map-${id}.install <<EOD
(cd0) $R/${iso}
(hd0) $D/${disk}
EOD

    cat > device.map-${id}.run <<EOD
(cd0) /fake
(hd0) $D/${disk}
EOD


    if test "$1" = "install"
    then
        _cmd=install-linux
        _ddev=`newvol $disk $size`
        if test -n "$grubi"
        then
            _g="-G $grubi"
        else
            _g=
        fi
        _d=$_devmapi
    else
        _cmd=run-linux
        _ddev=`getvol $disk`
        if test -n "$grubr"
        then
            _g="-G $grubr"
        else
            _g=
        fi
        _d=$_devmapr
        iso=
    fi

    #my-vmctl -P0:$cpu $_cmd $_g $_d $iso $_ddev $mac $name $cdev
    my-vmctl -M1 $_cmd $_g $_d $iso $_ddev $mac $name $cdev
}

run_simple_freebsd_preset () {
    local _cmd _ddev
    my-vmctl destroy $name
    if test "$1" = "install"
    then
        _cmd=install
        _ddev=`newvol $disk $size`
    else
        _cmd=run
        _ddev=`getvol $disk`
        iso=
    fi

    #my-vmctl -P0:$cpu $_cmd $iso $_ddev $mac $name $cdev
    my-vmctl -M1 $_cmd $iso $_ddev $mac $name $cdev
}

run_simple_windows_preset () {
    local _cmd _ddev
    my-vmctl destroy $name
    if test "$1" = "install"
    then
        _cmd=install-windows
        _ddev=`newvol $disk $size`
    else
        _cmd=run-windows
        _ddev=`newvol $disk $size`
        if test -z "$fakeiso"
        then
            fakeiso=.fakeiso-$name
        fi
        :> $fakeiso
        iso=$fakeiso
    fi

    export DEBUG=yes

    #my-vmctl -P0:$cpu $_cmd $bootrom $iso $_ddev $mac $name 
    my-vmctl -M1 $_cmd $bootrom $iso $_ddev $mac $name 
}

cdev="$idx"
midx=`printf "%02x" $idx`
id=${tag}.${midx}
name=vm-${id}
size=32G
cpu=$idx
mac=58:9c:fc:ea:00:$midx
disk=.diskdev-${id}
