#!/bin/sh

#set -x

MY_VMCTL_DDEV_UFS=1
mnvm_net=10.1.2
#mnvm_net=10.1.3

idx=$2
test -n "$idx" || exit 1
mnvm_node_id=$(( 100 + $idx ))

tag=freebsd-11
iso=FreeBSD-11.1-RELEASE-amd64-bootonly.iso
idbase=${tag}.00@base

. ./my-vmctl-preset-subr
run_simple_freebsd_preset $*
