#!/bin/sh

MY_VMCTL_DDEV_UFS=1
mnvm_net=10.1.2

#set -x
idx=$2
test -n "$idx" || exit 1
idx=$((32 + $idx))
mnvm_node_id=$(( 100 + $idx ))

tag=centos-7
iso=CentOS-7-x86_64-Everything-1708.iso
idbase=${tag}.20@base

. ./my-vmctl-preset-subr
run_simple_uefi_preset $*
